[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    robtillaart/INA226@^0.6.0

build_flags =
    -Isrc

[env:native]
platform = native
test_framework = unity

build_flags =
    -Isrc

test_build_src = yes

build_src_filter =
    +<memory/>
    +<navigation/>
    +<utils/>
    +<motors/motors.cpp>
    +<motors/sim_motors.cpp>
    +<sensors/battery.cpp>
    +<sensors/sim_sensors.cpp>
    +<sensors/rgb_sensor.cpp>

    -<main.cpp>
    -<test_runner.cpp>
    -<tasks/>
    -<communication/>
    -<motors/hal_motors.cpp>
    -<sensors/hal_sensors.cpp>

[env:esp32dev_test]
extends = env:esp32dev
build_flags =
    -Isrc
    -DTEST_MODE=1
build_src_filter =
    +<memory/>
    +<navigation/>
    +<test_runner.cpp>
    -<main.cpp>
    -<tasks/>
    -<communication/>
