[env:native] // Simulação nativa sem hardware
platform = native

build_flags =
    -D SIMULATION_MODE

test_framework = unity
test_build_src = true

; ======================================================

[env:esp32-sim] // ESP32 simulado
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

build_flags =
    -D SIMULATION_MODE

lib_deps =
    robtillaart/INA226

test_framework = unity
test_build_src = true

; ======================================================

[env:esp32-real]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

lib_deps =
    robtillaart/INA226

test_framework = unity
test_build_src = true