[env:native]
platform = native

build_flags =
    -D SIMULATION_MODE

test_framework = unity

test_build_src = true


[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200

lib_deps =
    robtillaart/INA226

build_flags =
    -D SIMULATION_MODE